### PR TITLE
Enable ppc64le

### PR DESCRIPTION
**Pull request by jayfurmanek**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Re-render the feedstock to pick up ppc64le support.

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@martinandersen FYI

**Comment by jakirkham** [comment]
Looks like this was handled in PR ( https://github.com/conda-forge/dsdp-feedstock/pull/7 ). Happy to close?

**Comment by jayfurmanek** [comment]
Awesome thanks!

**Pull request closed without merging**
