### PR TITLE
Add Windows build

### PR DESCRIPTION
**Pull request by martinandersen**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

Creating pull request to continue work on getting Windows build in feedstock; see #1
 
xref: conda-forge/staged-recipes#5729

### CODE REVIEW

**Comment by martinandersen** [comment]
@jakirkham, I added back the Windows build that we skipped in `staged-recipes`—it appears to works now so maybe there is no issue after all?

**Comment by jakirkham** [comment]
Interesting. Do you remember the issue we had there?

Looks good. Are we able to build with VS 2008 too?

**Comment by martinandersen** [comment]
The issue was a conflict related to `openblas`:
https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.23748#L928

I'm not sure VS 2008 is going to work since `openblas` requires `vc14`.

**Comment by jakirkham** [comment]
Right, sorry, forgot about that. Thanks for reminding me. :)

**Comment by jakirkham** [comment]
How did you generate `dsdp.def`?

**Comment by martinandersen** [comment]
First I tried passing `-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE` to CMake (>=3.4), but some symbols were missing, so I ended up manually creating the module definition file based on the header files in the `include` directory. I am not a Windows user, so I don't know if there is a better way.

**Comment by martinandersen** [comment]
The only thing that is in the DLL based on the "manual" module definition file but *not* in the CMake's autogenerated one is `dsdpoutputfile`. Enabling `WINDOWS_EXPORT_ALL_SYMBOLS` results in a lot of symbols that are not defined in the header files being exported.

**Comment by jakirkham** [comment]
I see. Thanks for the info.

@isuruf, do you mind taking a look at this?

**Comment by martinandersen** [comment]
On a related note, I left out the `dsdp5` binary (`examples/readsdpa.c`) on Windows since it crashes  when linked against the dynamic library. There is no issue when linking against a static `dsdp` library. 

There is no issue with the dynamic library when CVXOPT links against it.

**Comment by msarahan** [comment]
Thanks @martinandersen and @jakirkham - looks good to me.

**Comment by jakirkham** [comment]
Thanks for looking, Mike. Was hoping someone with better knowledge of Windows would take a look. :)

**Pull request merged**
